version: '3.1'
services:
  db:
    image: mysql:latest
    container_name: strattonapp-bbdd
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: strattonapp
    volumes:
     - mysql_data:/data/db

  strattonapp_back:
    build:
      context: ./Backend
      dockerfile: ./Dockerfile
    container_name: strattonapp_back
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      BBDD_HOST: db
      BBDD_NAME: strattonapp
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      APP_PORT: 8080
      LOG_LEVEL: DEBUG
      DLL_AUTO: create
    volumes:
      - ./src/main/resources:/app/resources
    depends_on:
      - db

  strattonapp_front:
    build:
      context: ./Frontend
      dockerfile: ./Dockerfile
    container_name: strattonapp_front
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - strattonapp_back

volumes:
  mysql_data:
  