version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: strattonapp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: strattonapp
      MYSQL_USER: kike
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: